apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-base
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - name: nginx-port
          containerPort: 80
