apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: dev
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: nginx
  type: ClusterIP
  clusterIP: None
