apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-volume
  labels:
    type: local
spec:
  storageClassName: wordpress
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  #hostPath:
  #  path: "/mnt/data"
  nfs:
    path: /wordpress
    server: 192.168.92.135

